<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>PersistX</PackageId>
		<PackageVersion>2.0.0</PackageVersion>
		<Authors>Farhan Lodi</Authors>
		<Description>High-performance persistent collection library with ACID transactions, indexing, and advanced data structures</Description>
		<PackageTags>persistent;collections;database;storage;indexing;transactions</PackageTags>
		<RepositoryUrl>https://github.com/FarhanLodi/PersistX</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageIcon>PersistX.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Text.Json" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
		<PackageReference Include="MessagePack" Version="3.1.7" />
	</ItemGroup>
	<ItemGroup>
		<None Include="../../assets/PersistX.png" Pack="true" PackagePath="" />
		<None Include="../../README.md" Pack="true" PackagePath="" />
	</ItemGroup>
</Project>
